# === Stage 53: Add command help text and usage examples ===
# Project: NoteShelf
HELP_TEXT = (
    "NoteShelf - Personal Note Shelf\n"
    "Usage: python notes.py <command> [options]\n\n"
    "Commands:\n"
    "  add <title> [--content <text>] [--folder <name>] [--tag <tag>] [--pin] [--priority <1-5>]\n"
    "  list [--folder <name>] [--tag <tag>] [--search <query>] [--pin]\n"
    "  view <note_id>\n"
    "  edit <note_id> <title> [--content <text>]\n"
    "  delete <note_id>\n"
    "  pin <note_id>\n"
    "  unpin <note_id>\n"
    "  search <query>\n"
    "  tags\n"
    "  folders\n"
    "  help\n\n"
    "Options:\n"
    "  --folder <name>    Add note to a specific folder\n"
    "  --tag <tag>        Add a tag to the note\n"
    "  --pin              Pin the note\n"
    "  --priority <1-5>   Set priority level\n"
    "  --search <query>   Search for notes\n"
    "  --help             Show this help message\n\n"
    "Examples:\n"
    "  python notes.py add 'Meeting Notes' --content 'Discuss Q4 goals' --tag work --priority 3\n"
    "  python notes.py list --folder work --tag urgent\n"
    "  python notes.py search 'project deadline'\n"
    "  python notes.py view 1\n"
    "  python notes.py edit 1 'Updated Meeting Notes' --content 'Added action items'\n"
    "  python notes.py delete 1\n"
    "  python notes.py pin 2\n"
    "  python notes.py unpin 3\n"
    "  python notes.py tags\n"
    "  python notes.py folders\n"
    "  python notes.py help\n"
)
